[package]
name = "blame"
version = "0.1.0"
authors = ["randy"]

[dependencies]
git2 = { git = "https://github.com/alexcrichton/git2-rs" }
hyper = "0.10.0"
hyper-native-tls = "0.2.1"
rustc-serialize = "0.3.22"

[dependencies.nickel]
version = "*"
